#!/usr/bin/env bash

repo="$1"
post_receive_hook_script="$(dirname $0)/pushand_post-receive_hook"

# If the remote repository doesn't exist, create it:
if [[ ! -d "$repo" ]]; then
  go_back="$(pwd)"
  mkdir -p $repo

  cd "$repo"

  # Initialize repository:
  git init > /dev/null
  git config core.bare false
  git config receive.denycurrentbranch ignore

  # Remove '.git/hooks/post-receive' if it exists: (which it will in certain git versions)
  rm -f .git/hooks/post-receive

  ln -s $post_receive_hook_script .git/hooks/post-receive > /dev/null
  cd "$go_back"
fi

# TODO: make this dynamic using the pushand_server_variables.
# Make the real call to the real git-receive-pack:
/usr/bin/git-receive-pack_original/git-receive-pack $*
