#!/usr/bin/env bash

if [ $1 ]; then
  SERVER=$1
else
  echo "Provide the server to test. (Eg. deploy@example.com)
!! Setting the option NO_PUSHAND disables '.pushand' command.
!! You need sudo access because pushand is uninstalled and installed."
  exit
fi

echo "=> Connect to '$SERVER' server and install pushand:"
ssh $SERVER <<EOF
pushd \$(mktemp -d /tmp/pushand.install.XXXXXXXXXX)
  git clone git://github.com/fesplugas/pushand.git
  cd pushand
  sudo ./bin/pushand uninstall
  sudo ./bin/pushand install
popd
EOF

echo "=> Create a local repo and push it to the server:"
pushd $(mktemp -d /tmp/pushand.XXXXXXXXXX)
  git init

  if [ ! $NO_PUSHAND ]; then
    echo "=> Create a '.pushand' file and make it executable:"
    cat > \.pushand << EOF
#!/usr/bin/env bash
echo "Hello from '.pushand' ... this file is \$0"
EOF
  else
    touch "README.md"
  fi

  echo "=> Add file to git and commit it:"
  git add .
  git commit -m 'First Commit'

  echo "=> Add a remote to git and verify it's correct:"
  git remote add pushand $SERVER:$(pwd)
  git remote -v

  echo "=> Push the repo:"
  git push pushand master
popd
